In [1]:
import numpy
print(numpy.__version__)

1.26.0


In [4]:
import numpy as np
arr1 = np.arange(10)
arr2 = np.arange(12).reshape(3,4)
arr3 = np.arange(24).reshape(2,4,3)

print(arr1)
print(arr2)
print(arr3)

[0 1 2 3 4 5 6 7 8 9]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [5]:
print(arr1[::])
print(arr1[::-1])
print(arr1[2::2])

[0 1 2 3 4 5 6 7 8 9]
[9 8 7 6 5 4 3 2 1 0]
[2 4 6 8]


2D array slicing:- 

In [7]:
print(arr2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [6]:
print(arr2[-1::-2,-1::-3])

[[11  8]
 [ 3  0]]


In [8]:
print(arr2[1::1,0::2])

[[ 4  6]
 [ 8 10]]


In [9]:
print(arr2[0,:])
print(arr2[:,0])
print(arr2[1:,1:])
print(arr2[::2,:2:])

[0 1 2 3]
[0 4 8]
[[ 5  6  7]
 [ 9 10 11]]
[[0 1]
 [8 9]]


3D array Slicing

In [14]:
print(arr3)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [15]:
arr3[1,1::2,::2]

array([[15, 17],
       [21, 23]])

In [16]:
print(arr3[0])
print(arr3[0,0])
print(arr3[1,:3])
print(arr3[0,:2,::2])

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[0 1 2]
[[12 13 14]
 [15 16 17]
 [18 19 20]]
[[0 2]
 [3 5]]


In [17]:
print(arr3[::,::3,::2])
print(arr3[::-1,-2::-2,-1::-2])

[[[ 0  2]
  [ 9 11]]

 [[12 14]
  [21 23]]]
[[[20 18]
  [14 12]]

 [[ 8  6]
  [ 2  0]]]


In [19]:
print(arr3[::-1,-2::-1,-2::-1])

[[[19 18]
  [16 15]
  [13 12]]

 [[ 7  6]
  [ 4  3]
  [ 1  0]]]


In [20]:
a1 = np.array([1,2,3])
a2 = np.array([1.1,2.2,3.3,4.4])

print(a1.dtype)
print(a2.dtype)

print(a1.itemsize)
print(a2.itemsize)

print(a1.nbytes)
print(a2.nbytes)

int32
float64
4
8
12
32


In [22]:
a1 = np.array([1,2,3,4])
a2 = np.array([[1,2,3,4,5],[6,7,8,9,0]])

print(a1.ndim)
print(a2.ndim)

print(a1.shape)
print(a2.shape)

print(a1.size)
print(a2.size)


1
2
(4,)
(2, 5)
4
10


numpy Array functions:-

In [ ]:
print(np.zeros(10))

print(np.zeros((3,6),dtype='int'))  #by default it takes floating point zeros

print(np.zeros((2,3,2)))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [ ]:
print(np.ones(10))

print(np.ones((3,6),dtype='int'))  #by default it takes floating point ones

print(np.ones((2,3,2)))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1 1 1 1 1 1]
 [1 1 1 1 1 1]
 [1 1 1 1 1 1]]
[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [27]:
print(np.identity(4,dtype='int'))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]
