In [1]:
import numpy as np
print(np.__version__)

1.26.0


Arithmetic operations with numpy array

In [2]:
a1 = np.array([1,3,5,7])
a2 = np.array([2,4,6,8])
print(a1)
print(a2)

[1 3 5 7]
[2 4 6 8]


Scalar Operations:- 

In [4]:
print(a1+5)
print(a1-5)
print(a1*2)
print(a1/2)
print(a1//2)
print(-a1)
print(a1**2)
print(a1%2)

[ 6  8 10 12]
[-4 -2  0  2]
[ 2  6 10 14]
[0.5 1.5 2.5 3.5]
[0 1 2 3]
[-1 -3 -5 -7]
[ 1  9 25 49]
[1 1 1 1]


In [5]:
print(a1+a2)
print(a1-a2)
print(a1*a2)
print(a1/a2)
print(a1//a2)
print(-a1)
print(a1**a2)
print(a1%a2)

[ 3  7 11 15]
[-1 -1 -1 -1]
[ 2 12 30 56]
[0.5        0.75       0.83333333 0.875     ]
[0 0 0 0]
[-1 -3 -5 -7]
[      1      81   15625 5764801]
[1 3 5 7]


In [6]:
print(np.dot(a1,a2))

100


In [8]:
arr1 = np.arange(12).reshape(3,4)
arr2 = np.arange(12).reshape(4,3)

print(arr1)
print(arr2)

print(np.dot(arr1,arr2))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[ 42  48  54]
 [114 136 158]
 [186 224 262]]


In [10]:
x = np.arange(20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [11]:
np.mean(x,axis=0) #axis = 0 is for column

array([ 7.5,  8.5,  9.5, 10.5, 11.5])

In [13]:
np.mean(x,axis=1)

array([ 2.,  7., 12., 17.])

In [14]:
np.min(x)

0

In [17]:
print(np.min(x,axis=0))

[0 1 2 3 4]


In [18]:
print(np.min(x,axis=1))

[ 0  5 10 15]


In [19]:
print(np.max(x))

19


In [20]:
print(np.max(x,axis=0))

[15 16 17 18 19]


In [21]:
print(np.max(x,axis=1))

[ 4  9 14 19]


In [23]:
print(np.sum(x))

190


In [24]:
print(np.sum(x,axis=0))

[30 34 38 42 46]


In [25]:
print(np.sum(x,axis=1))

[10 35 60 85]


In [26]:
p25 = np.percentile(x,25)
p50 = np.percentile(x,50)
p75 = np.percentile(x,75)
p100 = np.percentile(x,100)

print("25th Percentile:- ",p25)
print("50th Percentile:- ",p50)
print("75th Percentile:- ",p75)
print("100th Percentile:- ",p100)

25th Percentile:-  4.75
50th Percentile:-  9.5
75th Percentile:-  14.25
100th Percentile:-  19.0


Iterating through an array:-

In [28]:
arr1 = np.array([1,2,3,4,5,6])
for i in arr1:
  print(i,end=" ")

1 2 3 4 5 6 

In [29]:
arr1 = np.arange(20).reshape(4,5)
for i in arr1:
  print(i)

[0 1 2 3 4]
[5 6 7 8 9]
[10 11 12 13 14]
[15 16 17 18 19]


In [40]:
arr1 = np.arange(20).reshape(4,5)
count = 5
counter = 0
for i in arr1:
  arr1[counter]=i+count
  counter+=1
  count+=5
print(arr1)

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]]


In [42]:
arr1 = np.arange(20).reshape(4,5)
count = 5
for i in range(0,len(arr1),):
  arr1[i]=arr1[i]+count
  count+=5
print(arr1)

[[ 5  6  7  8  9]
 [15 16 17 18 19]
 [25 26 27 28 29]
 [35 36 37 38 39]]


Stacking of numpy array:-

In [47]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

In [48]:
a3 = np.hstack((a1,a2))
print(a3)

[[ 0  1  2  3 12 13 14 15]
 [ 4  5  6  7 16 17 18 19]
 [ 8  9 10 11 20 21 22 23]]


In [49]:
a3 = np.vstack((a1,a2))
print(a3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


Splitting in an Array:-

In [58]:
a1 = np.arange(24).reshape(6,4)
print(a1)
print(np.hsplit(a1,2))
print(np.hsplit(a1,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13],
       [16, 17],
       [20, 21]]), array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])]
[array([[ 0],
       [ 4],
       [ 8],
       [12],
       [16],
       [20]]), array([[ 1],
       [ 5],
       [ 9],
       [13],
       [17],
       [21]]), array([[ 2],
       [ 6],
       [10],
       [14],
       [18],
       [22]]), array([[ 3],
       [ 7],
       [11],
       [15],
       [19],
       [23]])]


In [59]:
a1 = np.arange(24).reshape(6,4)
print(a1)
print(np.vsplit(a1,2))
print(np.vsplit(a1,3))
print(np.vsplit(a1,6))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
[array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]]), array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])]
[array([[0, 1, 2, 3],
       [4, 5, 6, 7]]), array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]]), array([[16, 17, 18, 19],
       [20, 21, 22, 23]])]
[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]]), array([[16, 17, 18, 19]]), array([[20, 21, 22, 23]])]


WAP which makes an array having corresponding max value out of two given arrays:-
Input:-
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])

Output:-
[6,3,1,7,8]

In [64]:
a = np.array([6,3,1,5,8])
b = np.array([3,2,1,7,2])
c = list()
for i in range(0,len(a),1):
  c.append(max(a[i],b[i]))
print(c)

[6, 3, 1, 7, 8]


Write a python function that accepts infinite number of numpy arrays and do the vertical stack to them. Then return that new array as result. The functions only accepts the numpy array, otherwise raise error.

In [6]:
import numpy as np
def vs_infinite_array(*array):
  vs_array = np.vstack(array)
  return vs_array

a1 = np.array([1,2,3,4,5,6])
a2 = np.array([2,3,4,5,6,2])
a3 = np.array([5,3,5,2,1,5])
a4 = np.array([0,2,5,2,6,3])

a5 = vs_infinite_array(a1,a2,a3,a4)
print(a5)
print(type(a5))

[[1 2 3 4 5 6]
 [2 3 4 5 6 2]
 [5 3 5 2 1 5]
 [0 2 5 2 6 3]]
<class 'numpy.ndarray'>
