Numpy:-(CRUD operations) it has a class named nd(n-dimensional) array

In [1]:
import numpy
print(numpy.__version__)

1.26.0


Creating an Array:-

In [2]:
import numpy as np
x = np.array([1,2,3,4,5,6])
print(x)
print(type(x))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [3]:
y = np.arange(10)
print(y)

[0 1 2 3 4 5 6 7 8 9]


In [5]:
y = np.arange(-5,-10,-20)
print(y)

[-5]


In [10]:
x = np.random.random(size = (4,3))
print(x)

[[0.30503534 0.42474074 0.59176833]
 [0.82780572 0.7892385  0.90893877]
 [0.39492478 0.91996762 0.9449553 ]
 [0.01436329 0.36569895 0.46639498]]


In [ ]:
x = np.random.randint(50,size = (4,3)) #it'll take two arguments max range and size
print(x)

[[31 23 42]
 [48 36 46]
 [15 29 32]
 [ 4  1 30]]


WAP to create 3D numpy array with the dimension of 3x3x3 having values in between 15-20

In [16]:
x = np.random.randint(15,20,size=(3,3,3))
print(x)

[[[17 15 15]
  [17 19 16]
  [17 17 16]]

 [[16 17 18]
  [18 15 16]
  [16 17 17]]

 [[18 19 19]
  [16 16 17]
  [17 15 18]]]


In [17]:
x = np.arange(-15,66,20)
print(x)

[-15   5  25  45  65]


In [22]:
x = np.arange(20).reshape(2,10)
print(x)
x = np.arange(20).reshape(5,4)
print(x)
x = np.arange(20).reshape(1,20)
print(x)


x = np.arange(20).reshape(2,2,5)
print(x)

#in reshape it the multiplication of the no. of elements in the new shaped array of another dimension should be equal to the original 1D one

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]


In [26]:
x = np.arange(20).reshape(2,2,5)
print(x)
print(x[-1][-1][4])
print(x[-2][-1][-5])
print(x[0][0][4])
print(x[0][-2][-2])
print(x[-2][-2][-2])

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]]
19
5
4
3
3
